site_name: AgentOps Spec-Trace
theme:
  name: material
nav:
  - Home: index.md
  - Spec: specs/generated/app-spec-v0.0.1.md
  - Coding Agent Brief: specs/generated/coding-agent-brief-v0.0.1.md
  - Orchestration Plan: specs/generated/orchestration-plan-v0.0.1.md
  - RTM: rtm.md
  - ADRs:
      - ADR-0001: adr/ADR-0001.md
