name: Auto-merge on /merge
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: gate
        uses: ./.github/actions/load-env
        with:
          required-flags: ENABLE_AUTO_MERGE_WORKFLOW
      - if: steps.gate.outputs.skip == 'true'
        run: echo "Auto-merge workflow disabled."
      - if: steps.gate.outputs.skip != 'true'
        run: |
          if [[ ! "${{ github.event.comment.body || '' }}" =~ (^|\s)/merge(\s|$) ]]; then
            echo "No /merge command; skipping."; exit 78; fi
      - id: pr
        if: steps.gate.outputs.skip != 'true'
        run: |
          pr="$(jq -r '.issue.number // empty' "$GITHUB_EVENT_PATH")"
          echo "pr=$pr" >> $GITHUB_OUTPUT
      - if: steps.gate.outputs.skip != 'true' && steps.pr.outputs.pr != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          curl -sSL -X PUT -H "Authorization: Bearer $GH_TOKEN" -H "Content-Type: application/json"             -d '{"merge_method":"squash"}'             "https://api.github.com/repos/$REPO/pulls/${{ steps.pr.outputs.pr }}/merge" | tee response.json
          jq -e '.merged == true' response.json >/dev/null || { echo "::error::Merge failed"; exit 1; }

