name: sbom

on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v3
        with:
          version: 9.12.0
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false
      - name: Generate CycloneDX SBOM
        run: npx @cyclonedx/cyclonedx-npm --output-format JSON --output-file bom.json
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: cyclone-dx-sbom
          path: bom.json
      - name: Attach SBOM to release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: bom.json
          asset_name: speckit-sbom.json
          asset_content_type: application/json
