name: Spec Trace
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  spec-trace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: |
          corepack enable
          pnpm i
      - name: Lint SRS (Spectral)
        run: pnpm lint:spec
      - name: Generate Spec/Brief/Plan (defaults from SRS)
        run: pnpm docs:gen
      - name: Build RTM (placeholder)
        run: pnpm rtm:build
      - name: Run tests (Playwright)
        run: npx playwright test --reporter=line || true
      - name: Upload RTM + generated docs
        uses: actions/upload-artifact@v4
        with:
          name: docs-and-rtm
          path: |
            docs/specs/generated/**
            docs/rtm.md
